---
services:
  mysql:
    image: mysql:latest
    container_name: mysql-intencao
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: intencao
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306   
    volumes:
      - mysql-data:/var/lib/mysql
  servico-de-produtos:
    container_name: servico-de-produtos
    build:
      context: ./servico-de-produtos
    image: servico-de-produtos
    ports:
      - 3000:8080
  servico-de-intencao:
    container_name: servico-de-intencao
    build:
      context: ./servico-de-intencao
    image: servico-de-intencao
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/intencao
    depends_on:
      - mysql
      
volumes:
  mysql-data: null